### ISSUE TITLE
Issue with Streak count

### ISSUE THREAD

**Issue by Aditya137x** [xpavle00/Habo#15]
So I noticed one bug when counting streak for an Habit which has two day rule enabled.

So if I skip a day then don't do the next day and then complete the habit the following day the streak continues. 

![5268f490-779e-4895-a26f-86a107c826dc](https://user-images.githubusercontent.com/111834313/216841114-5c1b56ca-edc7-420a-9b1a-8bdbd426cbf5.jpg)

But if I don't complete the habit today and skip the next day then the streak count resets.

![a8640295-ad11-4717-bb26-33b3f00ffef4](https://user-images.githubusercontent.com/111834313/216840918-ab160b4a-15eb-437a-ade7-d7440c56f5d6.jpg)

I am assuming it's a bug so reporting. Anyway, Thanks.

**Comment by xpavle00** [comment]
Hi, it is intended to be like this. The main meaning of the two-day rule is that if you do not complete one day, the next day must be green.
