### ISSUE TITLE
'Create habit' button obscuring UI on Android 10

### ISSUE THREAD

**Issue by lo-kiss** [xpavle00/Habo#19]
**Android version: 10
Habo version: 2.0.0**

# Problem
The 'create habit' button is obscuring the very last date at the bottom of the screen. I can still access the date if I scroll a little, but it is frustrating as it's just a bit of visibility.

*In the first screenshot 'do blender' was the last habit in the list and in the second screenshot 'ex' was the last habit in the list*

## Possible solution:
A very rough idea would be to add a bit of white space at the bottom so the button has space to be without obscuring the UI.

Thank you for your time!

## Screenshots
![20230212_221820](https://user-images.githubusercontent.com/115636509/218335007-9f3c3260-9fc2-4bc5-b313-fbf7a7f1055e.jpg)
![20230212_221839](https://user-images.githubusercontent.com/115636509/218335009-cc6c7782-788b-44a0-abce-2e9fd87133ac.jpg)

**Comment by xpavle00** [comment]
Hi,
**Thanks** for the report. It will be fixed in the next version.
