### ISSUE TITLE
"Show reward" info appears below the screen on Android 10 while textbox selected

### ISSUE THREAD

**Issue by PorterRyan** [xpavle00/Habo#2]
I'm on Android 10, and when creating a new habit, in the "Advanced habit building" drop-down the info box for "Show reward" appears below the screen if any of the textboxes are selected.

**Steps to reproduce**
Create a new habit, tap in one of the textboxes, then hold the info button next to "Show reward".

**Thoughts**
I'm not at all familiar with Flutter, but perhaps there's a way to insert newlines under the info box to force it into view while the keyboard is open?

**Comment by xpavle00** [comment]
Thanks a lot for the info. I will fix it in the next version.
