### ISSUE TITLE
"Punishment" for not doing the habit

### ISSUE THREAD

**Issue by mizzunet** [xpavle00/Habo#20]
Hi, I think it would be nice if we could set Punishment in Advanced habit building, for not doing the habit. 

For example, I want to wake up early, if I don't, I want to punish myself to force donate some certain money to some like Wikipedia or maybe for this project

Thanks for this awesome and pretty app. Greatly appreciated :)

**Comment by xpavle00** [comment]
From version 2.0.1 there is a "Habit contract" section for this purpose.
