### ISSUE TITLE
Compact list

### ISSUE THREAD

**Issue by mizzunet** [xpavle00/Habo#21]
Would you please add a setting to compact the list of habits to small size.

Thanks

**Comment by xpavle00** [comment]
Hey, I like the idea, but can you provide more details on how it should look like? :)

**Comment by 12people** [comment]
I personally really like [Loop Habit Tracker](https://github.com/iSoron/uhabits)'s table view:

![The table view in Loop Habit Tracker](https://github.com/iSoron/uhabits/blob/dev/screenshots/1.png?raw=true)

Perhaps something like this could be implemented?

**Comment by xpavle00** [comment]
This looks a bit compact. I prefer design language with a bit negative space.
