### ISSUE TITLE
Adaptive icon support 

### ISSUE THREAD

**Issue by lokesh-krishna** [xpavle00/Habo#23]
Would be really nice to have [adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) support.

**Comment by xpavle00** [comment]
Hey, adaptive icons should be supported.

**Comment by lokesh-krishna** [comment]
Do you mean it's already supported? On my Pixel 6 running Android 13 (GrapheneOS), this is what the icon looks like:

![Screenshot_20230422-020906](https://user-images.githubusercontent.com/20235646/233730582-18775587-5930-4706-82ef-832930cbfd1a.png)

As you can see, the icon is not adaptive.

**Comment by xpavle00** [comment]
It looks the same as for example Gmail icon.
I think adaptive icons applies only to desktop icons in 13.

**Comment by lokesh-krishna** [comment]
It doesn't because Gmail provides a background layer (in this case, white). If Habo provided an actual background layer, we'd have a green background instead of the white background upon which the actual icon sits.

**Comment by xpavle00** [comment]
Habo provides also white background with green icon.

**Comment by lokesh-krishna** [comment]
The idea with the adaptive icon is that you have a background and a foreground. I don't think Habo is providing a background. So the icon as a whole is being set upon the white background. Habo has a green background, which if provided as a separate background would make an adaptive icon possible.

**Comment by xpavle00** [comment]
Habos logo is a green square with a white checkmark. A square is also important, it is not just a checkmark. This is intended. I provide a white background and it should be similar to for example Gmail or Docs on your screen. 
If you look at [UI guide ](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)you provided, a star shape is also in the foreground, with an android. The same idea is here, the Habo logo is foreground and it is set up to have a white background.

**Comment by lokesh-krishna** [comment]
Ah, understood!
