### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by 12people** [xpavle00/Habo#26]
It'd be great if Habo was translatable into different languages.

Once translation support is implemented in the code, Habo could be translated via Weblate, which has a [free tier for free and open-source projects](https://weblate.org/en/hosting/#libre).

**Comment by xpavle00** [comment]
Hey, it looks interesting. I will look at this. Thanks for the suggestion.

**Comment by xe1st** [comment]
@xpavle00 Hey! Can you add Turkish language to weblate? I don't see the *add a language* option.

**Comment by xpavle00** [comment]
> @xpavle00 Hey! Can you add Turkish language to weblate? I don't see the _add a language_ option.

Hey, it should be there now.

**Comment by xe1st** [comment]
> > @xpavle00 Hey! Can you add Turkish language to weblate? I don't see the _add a language_ option.
> 
> Hey, it should be there now.

Yes it is, thanks :)

**Comment by hachikoharuno** [comment]
@xpavle00  Hi, could you please add Russian for translation on Weblate.
