### ISSUE TITLE
Notifications not working on iOS?

### ISSUE THREAD

**Issue by antranigv** [xpavle00/Habo#27]
Hi! love the app!

I was wondering if the notifications are still not 'complete' on iOS? I just installed the app, but seems like I'm not getting any notifications.

For now, I could just use Shortcuts.app to send notifications, but I was wondering if it's a bug or not :)

**Comment by xpavle00** [comment]
Hey,
notifications should work on IOS, I had no problem with them on my testing devices and also did not hear anything from testers.
Did you allow notifications when the app was installed?

**Comment by antranigv** [comment]
Okay, I just did a reinstall and it prompted and it all works fine! thank you!

I think it would be a good idea to have a button that shows the prompt whenever a user enables/disables notifications in the settings page.

This was my first thought as well, but I was not able to find the app in the Settings. Now that notifications work, I do see the app in Settings :D

**Comment by xpavle00** [comment]
I am glad it works now :)
So I am closing this issue and I will think about some checks.
