### ISSUE TITLE
Any timeline for iOS?

### ISSUE THREAD

**Issue by chmac** [xpavle00/Habo#3]
App looks interesting on android. Any timeline on when an iOS release might be available?

Is there a flutter build that runs on iOS currently?

Thanks for sharing open source code.

**Comment by xpavle00** [comment]
Hey,
soon I will release some changes based on beta testing reviews. Then I hope I will start the process with the app store. So maybe in a month or two. But the app is tested on an iOS emulator and works like on Android. 
If you build it for yourself, it should work fine.

**Comment by mkhalila** [comment]
@xpavle00 Hello Peter. Just wondering if there’s any update on this? I’ve recently got an iPhone and I’m super keen for a privacy friendly OS habit tracker

**Comment by xpavle00** [comment]
Hey.
I fixed some issues and refactored a code. Now I am working on updates(statistics and backup). Then I want to finish beta testing and then I would like to start with the apple app store process. Hope it will be soon, but I can not give you an exact time for now.

**Comment by mkhalila** [comment]
Thanks for the swiftness and transparency of your response. I look forward to the release when it’s ready

**Comment by espetro** [comment]
Hi @xpavle00 , I'm also interested in using the app on iOS. Would it be possible to install via TestFlight? Or perhaps could you give us some instructions on how to build it locally and install it on our own? Thanks in advance 😄

**Comment by xpavle00** [comment]
Hey, it took a bit longer than I expected, but I have a TestFlight beta build.
https://testflight.apple.com/join/F39jE9eL
So I will be glad for any feedback.

**Comment by xpavle00** [comment]
Hey,
the app is live on App Store. 
https://apps.apple.com/us/app/habo-habit-tracker/id1670223360

**Comment by chmac** [comment]
Great news!

You may want to consider submitting the app to this open source iOS list:
https://github.com/dkhamsing/open-source-ios-apps
