### ISSUE TITLE
Bug on actual streak

### ISSUE THREAD

**Issue by henriqueio** [xpavle00/Habo#35]
First of all thank you for this amazing app.

I was using the app today when o saw this interesting thing.
To me sound like a little bug because my actual streak on this habit is 2 not 9. I failed on this habit 2 times, but the actual streak counter did not reset. 

![image](https://github.com/xpavle00/Habo/assets/32798723/edd66169-979f-46ca-b4a6-b61239b829db)

**Comment by xpavle00** [comment]
Hey, Thanks for the report.
Do you have a "Two-day rule" enabled? If so, this is correct behavior. You can have one "X" as soon as it is followed by "Check" and it won't affect your streak.

**Comment by henriqueio** [comment]
I have the two-day rules enabled, possibly I enabled it by accident! Thanks!
