### ISSUE TITLE
Habo clone on Play Store

### ISSUE THREAD

**Issue by ch3thanhs** [xpavle00/Habo#65]
I found a clone of this app on the Play Store - https://play.google.com/store/apps/details?id=work.mywild.Habits

The developer's apps are all just clones of other open-source projects with AI generated app icons.

The developer's GitHub - https://github.com/djacidfx

**Comment by ch3thanhs** [comment]
So, the developer's account seems to be suspended. I'll close this issue.

**Comment by xpavle00** [comment]
Thanks :)
