### ISSUE TITLE
Q: Can I go back a week to make edits?

### ISSUE THREAD

**Issue by richard-edwards** [xpavle00/Habo#69]
Just started using Habo and I'm impressed so far.

I have my week starting on Monday (today) and I don't seem to be able to go back to last week to set a missed status update for yesterday. Am I missing something or is this just not possible at the moment. It would be nice to have a running week where I can see the past couple of days and then today and out the next 4 days perhaps.

Thanks

**Comment by xpavle00** [comment]
Hey,
Thanks for using Habo :)
You can swipe right on week to show a week before. Or you can swipe down to show a full month.
![1 (1)](https://github.com/xpavle00/Habo/assets/7284227/a3380ba5-cf12-4cf2-8842-38b5a36c2c42)

**Comment by richard-edwards** [comment]
I swear I tried that .. haha works great. Thanks again.
